apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: numaflow-system

resources:
  - https://raw.githubusercontent.com/numaproj/numaflow/stable/config/install.yaml

patches:
  - target:
      kind: ConfigMap
      name: numaflow-controller-config
    patch: |-
      - op: replace
        path: /data
        value: 
  - target:
      kind: Deployment
      name: numaflow-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0
        value:
          name: unnecessary
          image: busybox
          command:
            - "/bin/sh"
            - "-c"
            - "while true; do echo hello; sleep 60; done"
