apiVersion: numaplane.numaproj.io/v1alpha1
kind: ISBServiceRollout
metadata:
  name: my-isbsvc
  namespace: demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  interStepBufferService:
    jetstream:
      version: latest
      persistence:
        volumeSize: 1Gi
