apiVersion: numaplane.numaproj.io/v1alpha1
kind: PipelineRollout
metadata:
  name: my-pipeline
  namespace: demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  pipeline:
    spec:
      interStepBufferServiceName: my-isbsvc
      vertices:
        - name: in
          source:
            generator:
              rpu: 5
              duration: 15s
        - name: cat
          udf:
            builtin:
              name: cat
        - name: out
          sink:
            log: {}
      edges:
        - from: in
          to: cat
        - from: cat
          to: out
