apiVersion: numaplane.numaproj.io/v1alpha1
kind: PipelineRollout
metadata:
  name: my-pipeline
  namespace: demo-app
spec:
  pipeline:
    interStepBufferServiceName: my-isbsvc
    vertices:
      - name: in
        source:
          generator:
            rpu: 5
            duration: 15s
      # - name: cat
      #   udf:
      #     builtin:
      #       name: cat
      - name: out
        sink:
          log: {}
    edges:
      - from: in
        to: cat
      - from: cat
        to: out
