apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  resource.customizations: |
    numaplane.numaproj.io/PipelineRollout:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "ChildResourcesHealthy" and condition.status == "False" then
                hs.status = "Degraded"
                hs.message = condition.message
                return hs
              end
              if condition.type == "ChildResourcesHealthy" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = condition.message
                return hs
              end
              if condition.type == "ChildResourcesHealthy" and condition.status == "Unknown" then
                hs.status = "Degrade"
                hs.message = condition.message
                return hs
              end
            end
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for Pipeline status"
        return hs
    numaplane.numaproj.io/ISBServiceRollout:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "ChildResourcesHealthy" and condition.status == "False" then
                hs.status = "Degraded"
                hs.message = condition.message
                return hs
              end
              if condition.type == "ChildResourcesHealthy" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = condition.message
                return hs
              end
              if condition.type == "ChildResourcesHealthy" and condition.status == "Unknown" then
                hs.status = "Degrade"
                hs.message = condition.message
                return hs
              end
            end
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for ISBService status"
        return hs
    numaplane.numaproj.io/NumaflowControllerRollout:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "All good!"
        return hs
