apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  resource.customizations: |
    numaplane.numaproj.io/PipelineRollout:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.phase ~= nil then
            if obj.status.phase == "Running" then
              hs.status = "Healthy"
              hs.message = "All good!"
            end
          end
        end
        return hs
    numaplane.numaproj.io/ISBServiceRollout:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.phase ~= nil then
            if obj.status.phase == "Running" then
              hs.status = "Healthy"
              hs.message = "All good!"
            end
          end
        end
        return hs
    numaplane.numaproj.io/NumaflowControllerRollout:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.phase ~= nil then
            if obj.status.phase == "Running" then
              hs.status = "Healthy"
              hs.message = "All good!"
            end
          end
        end
        return hs
